[package]
name = "axum_session_surreal"
version = "0.5.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "📝 Surreal Persistent Database layer for axum_session"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session_surreal"
keywords = ["Axum", "Tower", "Surreal", "Session"]
repository = "https://github.com/AscendingCreations/AxumSession"

[dependencies]
axum_session = "0.17.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde", "std"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
surrealdb = { version = "2.3" }
